node_lock.settings:
  type: config_object
  mapping:
    enabled:
      type: integer
      label: 'Enabled node lock service'
    bundles:
      type: sequence
      label: 'Bundle type'
      sequence:
        type: mapping
        mapping:
          bundle:
            type: string
            label: 'Bundle name'
